-- AlterTable
ALTER TABLE `notification` MODIFY `type` ENUM('WELCOME', 'APPOINTMENT_CREATED', 'APPOINTMENT_CONFIRMED', 'APPOINTMENT_CANCELLED', 'APPOINTMENT_COMPLETED', 'APPOINTMENT_STATUS_CHANGED', 'REVIEW_REQUEST', 'SYSTEM') NOT NULL;
