-- AlterTable
ALTER TABLE `notification` ADD COLUMN `type` ENUM('WELCOME', 'APPOINTMENT_CREATED', 'APPOINTMENT_CONFIRMED', 'APPOINTMENT_CANCELLED', 'APPOINTMENT_COMPLETED', 'REVIEW_REQUEST', 'SYSTEM') NOT NULL DEFAULT 'SYSTEM';
