# recueda levantar CMD ["sh", "-c", "ts-node src/index.ts & ts-node src/modules/appointments/appointment.worker.ts"]
 # para solo worker CMD ["ts-node", "src/modules/appointments/appointment.worker.ts"]
